spring.application.name=bookstore
server.port=8080

# spring - database
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3386/bookstore
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# 바인딩된 파라미터 로깅 설정
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=debug

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# 정적 파일 캐싱
spring.web.resources.cache.period=0


kakao.resetapi.key=e0b415dd4c54c47b8b91b3f0e643c76e

spring.data.redis.host=localhost
spring.data.redis.port=6379

